### ISSUE TITLE
Can't load DBCAPI Library

### ISSUE THREAD

**Issue by mtmcfarl** [sqlanywhere/sqlanywhere#2]
My Rails 2.3.5 app cannot load the DBCAPI library.  I'm connecting to a Sybase database.  I have sourced it:

/opt/sqlanywhere12/bin32/sa_config.sh

script/console production seems to work as I can call methods and get back data.

**Comment by sqlanywhere** [comment]
Hello,

What operating system and version are you using?

The fact that you are able to get back data using the console suggests that in some cases, the system is able to find the DBCAPI library. When it throws up the error, are you trying to run as a different user or a super user?

Thanks,
- Eric

**Comment by mtmcfarl** [comment]
Hi Eric,

The production rails stack is Ubuntu 10.04 LTS.  Running Rails 2.3.5.  I know that when I source it I'm using user brandon in group brandon.  This user brandon is also a part of the www-data group.  I can't say for certain what user rails is running under.  Is there a way to tell?  Thanks for your help!

**Comment by mtmcfarl** [comment]
Turns out I had to source the database in /etc/init.d/thin.

All is well.
